# Publish to PyPI via Trusted Publishing (manual run only)
name: Publish Package to PyPI

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to PyPI"
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build tool
        run: pip install hatch

      - name: Build distributions
        run: hatch build  # outputs dist/*

      - name: Inspect build artifacts (optional)
        run: |
          ls -lh dist/
          file dist/* || true

      - name: Validate metadata (optional)
        run: |
          pip install twine
          twine check dist/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.publish }}  # Only run when the checkbox is ticked
    environment:
      name: pypi
      url: https://pypi.org/p/llama-index-vector-stores-zeusdb
    permissions:
      id-token: write   # required for Trusted Publishing
      contents: read
    steps:
      - name: Download built dists
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI (attestations enabled by default)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          # attestations: false   # only set if you explicitly need to disable
